name: appsync-test
schema: appsync/schema.graphql
authentication:
  type: AMAZON_COGNITO_USER_POOLS
  config:
    awsRegion: us-east-2
    defaultAction: ALLOW
    userPoolId: !Ref UserPool
additionalAuthentications:
  - type: AWS_IAM
logging:
  logginRoleArn: !GetAtt AppSyncLoggingServiceRole.Arn
  level: ERROR
  excludeVerboseContent: false
xrayEnabled: false

resolvers:
  # Cards
  Query.getCard:
    dataSource: cardsTable
    kind: UNIT
    request: appsync/mappings/Query.getCard.request.vtl
    response: appsync/mappings/Query.getCard.response.vtl

dataSources:
  cardsTable:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref CardsTable
